// 브랜드 기준 데이터 88개
// = 로고 모음 시트에서 확인한 카드 021~100의 80개 + 그 카드에 없던 SPA 8개(택 데이터 수집 대상)
// 카드 001~020은 파일이 없어 미확인 (확보하면 여기에 추가)
// 용도: (1) 브랜드 사전 자동 확장  (2) 인식 실패 시 브랜드 후보 제시  (3) 공식몰 이동
// name: 표기명, ko: 한글명, cat: 분류, domain: 공식몰
window.BRAND_CATALOG = [
  // 1차 목표 SPA 브랜드 8개 (로고 카드 021~100에는 없음. MUJI는 카드 035에 있어 아래 목록에 둠)
  { name: 'ZARA', ko: '자라', cat: 'SPA/데일리', domain: 'zara.com' },
  { name: 'UNIQLO', ko: '유니클로', cat: 'SPA/데일리', domain: 'uniqlo.com' },
  { name: 'H&M', ko: '에이치앤엠', cat: 'SPA/데일리', domain: 'hm.com' },
  { name: 'COS', ko: '코스', cat: 'SPA/데일리', domain: 'cos.com' },
  { name: 'ARKET', ko: '아르켓', cat: 'SPA/데일리', domain: 'arket.com' },
  { name: 'SPAO', ko: '스파오', cat: 'SPA/데일리', domain: 'spao.com' },
  { name: '8SECONDS', ko: '에잇세컨즈', cat: 'SPA/데일리', domain: '8seconds.co.kr' },
  { name: 'MUSINSA STANDARD', ko: '무신사 스탠다드', cat: 'SPA/데일리', domain: 'musinsa.com' },

  // SPA / 데일리 (카드 021~035)
  { name: 'Mango', ko: '망고', cat: 'SPA/데일리', domain: 'mango.com' },
  { name: 'GU', ko: '지유', cat: 'SPA/데일리', domain: 'gu-global.com' },
  { name: 'Bershka', ko: '베르쉬카', cat: 'SPA/데일리', domain: 'bershka.com' },
  { name: 'Pull&Bear', ko: '풀앤베어', cat: 'SPA/데일리', domain: 'pullandbear.com' },
  { name: 'Stradivarius', ko: '스트라디바리우스', cat: 'SPA/데일리', domain: 'stradivarius.com' },
  { name: 'Gap', ko: '갭', cat: 'SPA/데일리', domain: 'gap.com' },
  { name: 'Old Navy', ko: '올드네이비', cat: 'SPA/데일리', domain: 'oldnavy.com' },
  { name: 'Abercrombie & Fitch', ko: '아베크롬비', cat: 'SPA/데일리', domain: 'abercrombie.com' },
  { name: 'American Eagle', ko: '아메리칸이글', cat: 'SPA/데일리', domain: 'ae.com' },
  { name: 'Aritzia', ko: '아리치아', cat: 'SPA/데일리', domain: 'aritzia.com' },
  { name: 'J.Crew', ko: '제이크루', cat: 'SPA/데일리', domain: 'jcrew.com' },
  { name: 'Banana Republic', ko: '바나나리퍼블릭', cat: 'SPA/데일리', domain: 'bananarepublic.com' },
  { name: 'Urban Outfitters', ko: '어반아웃피터스', cat: 'SPA/데일리', domain: 'urbanoutfitters.com' },
  { name: 'Everlane', ko: '에버레인', cat: 'SPA/데일리', domain: 'everlane.com' },
  { name: 'MUJI', ko: '무인양품', cat: 'SPA/데일리', domain: 'muji.com' },

  // 스포츠 / 스니커즈 / 아웃도어 (카드 036~067)
  { name: 'Nike', ko: '나이키', cat: '스포츠/스니커즈/아웃도어', domain: 'nike.com' },
  { name: 'adidas', ko: '아디다스', cat: '스포츠/스니커즈/아웃도어', domain: 'adidas.com' },
  { name: 'New Balance', ko: '뉴발란스', cat: '스포츠/스니커즈/아웃도어', domain: 'newbalance.com' },
  { name: 'ASICS', ko: '아식스', cat: '스포츠/스니커즈/아웃도어', domain: 'asics.com' },
  { name: 'PUMA', ko: '푸마', cat: '스포츠/스니커즈/아웃도어', domain: 'puma.com' },
  { name: 'Reebok', ko: '리복', cat: '스포츠/스니커즈/아웃도어', domain: 'reebok.com' },
  { name: 'Under Armour', ko: '언더아머', cat: '스포츠/스니커즈/아웃도어', domain: 'underarmour.com' },
  { name: 'lululemon', ko: '룰루레몬', cat: '스포츠/스니커즈/아웃도어', domain: 'lululemon.com' },
  { name: 'On Running', ko: '온러닝', cat: '스포츠/스니커즈/아웃도어', domain: 'on.com' },
  { name: 'Salomon', ko: '살로몬', cat: '스포츠/스니커즈/아웃도어', domain: 'salomon.com' },
  { name: 'HOKA', ko: '호카', cat: '스포츠/스니커즈/아웃도어', domain: 'hoka.com' },
  { name: 'Converse', ko: '컨버스', cat: '스포츠/스니커즈/아웃도어', domain: 'converse.com' },
  { name: 'Vans', ko: '반스', cat: '스포츠/스니커즈/아웃도어', domain: 'vans.com' },
  { name: 'FILA', ko: '휠라', cat: '스포츠/스니커즈/아웃도어', domain: 'fila.com' },
  { name: 'Champion', ko: '챔피언', cat: '스포츠/스니커즈/아웃도어', domain: 'champion.com' },
  { name: 'The North Face', ko: '노스페이스', cat: '스포츠/스니커즈/아웃도어', domain: 'thenorthface.com' },
  { name: 'Patagonia', ko: '파타고니아', cat: '스포츠/스니커즈/아웃도어', domain: 'patagonia.com' },
  { name: "Arc'teryx", ko: '아크테릭스', cat: '스포츠/스니커즈/아웃도어', domain: 'arcteryx.com' },
  { name: 'Columbia', ko: '컬럼비아', cat: '스포츠/스니커즈/아웃도어', domain: 'columbia.com' },
  { name: 'Snow Peak', ko: '스노우피크', cat: '스포츠/스니커즈/아웃도어', domain: 'snowpeak.com' },
  { name: 'Montbell', ko: '몽벨', cat: '스포츠/스니커즈/아웃도어', domain: 'montbell.com' },
  { name: 'Helly Hansen', ko: '헬리한센', cat: '스포츠/스니커즈/아웃도어', domain: 'hellyhansen.com' },
  { name: 'Fjällräven', ko: '피엘라벤', cat: '스포츠/스니커즈/아웃도어', domain: 'fjallraven.com' },
  { name: 'Mammut', ko: '마무트', cat: '스포츠/스니커즈/아웃도어', domain: 'mammut.com' },
  { name: 'Merrell', ko: '메렐', cat: '스포츠/스니커즈/아웃도어', domain: 'merrell.com' },
  { name: 'Timberland', ko: '팀버랜드', cat: '스포츠/스니커즈/아웃도어', domain: 'timberland.com' },
  { name: 'Dr. Martens', ko: '닥터마틴', cat: '스포츠/스니커즈/아웃도어', domain: 'drmartens.com' },
  { name: 'Crocs', ko: '크록스', cat: '스포츠/스니커즈/아웃도어', domain: 'crocs.com' },
  { name: 'Birkenstock', ko: '버켄스탁', cat: '스포츠/스니커즈/아웃도어', domain: 'birkenstock.com' },
  { name: 'Skechers', ko: '스케쳐스', cat: '스포츠/스니커즈/아웃도어', domain: 'skechers.com' },

  // 캐주얼 / 데님 / 컨템포러리 (카드 066~085)
  { name: "Levi's", ko: '리바이스', cat: '캐주얼/데님/컨템포러리', domain: 'levis.com' },
  { name: 'Lee', ko: '리', cat: '캐주얼/데님/컨템포러리', domain: 'lee.com' },
  { name: 'Wrangler', ko: '랭글러', cat: '캐주얼/데님/컨템포러리', domain: 'wrangler.com' },
  { name: 'Carhartt WIP', ko: '칼하트 WIP', cat: '캐주얼/데님/컨템포러리', domain: 'carhartt-wip.com' },
  { name: 'Dickies', ko: '디키즈', cat: '캐주얼/데님/컨템포러리', domain: 'dickies.com' },
  { name: 'Polo Ralph Lauren', ko: '폴로 랄프로렌', cat: '캐주얼/데님/컨템포러리', domain: 'ralphlauren.com' },
  { name: 'Tommy Hilfiger', ko: '타미힐피거', cat: '캐주얼/데님/컨템포러리', domain: 'tommy.com' },
  { name: 'Calvin Klein', ko: '캘빈클라인', cat: '캐주얼/데님/컨템포러리', domain: 'calvinklein.com' },
  { name: 'Lacoste', ko: '라코스테', cat: '캐주얼/데님/컨템포러리', domain: 'lacoste.com' },
  { name: 'Fred Perry', ko: '프레드페리', cat: '캐주얼/데님/컨템포러리', domain: 'fredperry.com' },
  { name: 'Paul Smith', ko: '폴스미스', cat: '캐주얼/데님/컨템포러리', domain: 'paulsmith.com' },
  { name: 'Diesel', ko: '디젤', cat: '캐주얼/데님/컨템포러리', domain: 'diesel.com' },
  { name: 'G-Star RAW', ko: '지스타로우', cat: '캐주얼/데님/컨템포러리', domain: 'g-star.com' },
  { name: 'Superdry', ko: '수퍼드라이', cat: '캐주얼/데님/컨템포러리', domain: 'superdry.com' },
  { name: 'ALLSAINTS', ko: '올세인츠', cat: '캐주얼/데님/컨템포러리', domain: 'allsaints.com' },
  { name: 'A.P.C.', ko: '아페쎄', cat: '캐주얼/데님/컨템포러리', domain: 'apc.fr' },
  { name: 'Acne Studios', ko: '아크네 스튜디오', cat: '캐주얼/데님/컨템포러리', domain: 'acnestudios.com' },
  { name: 'Maison Kitsuné', ko: '메종키츠네', cat: '캐주얼/데님/컨템포러리', domain: 'maisonkitsune.com' },
  { name: 'AMI Paris', ko: '아미', cat: '캐주얼/데님/컨템포러리', domain: 'amiparis.com' },
  { name: 'Stone Island', ko: '스톤아일랜드', cat: '캐주얼/데님/컨템포러리', domain: 'stoneisland.com' },

  // 스트리트 / 디자이너 (카드 086~100)
  { name: 'Stüssy', ko: '스투시', cat: '스트리트/디자이너', domain: 'stussy.com' },
  { name: 'Supreme', ko: '슈프림', cat: '스트리트/디자이너', domain: 'supremenewyork.com' },
  { name: 'Palace', ko: '팰리스', cat: '스트리트/디자이너', domain: 'palaceskateboards.com' },
  { name: 'BAPE', ko: '베이프', cat: '스트리트/디자이너', domain: 'bape.com' },
  { name: 'Kith', ko: '키스', cat: '스트리트/디자이너', domain: 'kith.com' },
  { name: 'Fear of God', ko: '피어오브갓', cat: '스트리트/디자이너', domain: 'fearofgod.com' },
  { name: 'Off-White', ko: '오프화이트', cat: '스트리트/디자이너', domain: 'off---white.com' },
  { name: 'C.P. Company', ko: 'CP컴퍼니', cat: '스트리트/디자이너', domain: 'cpcompany.com' },
  { name: 'Human Made', ko: '휴먼메이드', cat: '스트리트/디자이너', domain: 'humanmade.jp' },
  { name: 'KENZO', ko: '겐조', cat: '스트리트/디자이너', domain: 'kenzo.com' },
  { name: 'Marni', ko: '마르니', cat: '스트리트/디자이너', domain: 'marni.com' },
  { name: 'Burberry', ko: '버버리', cat: '스트리트/디자이너', domain: 'burberry.com' },
  { name: 'Prada', ko: '프라다', cat: '스트리트/디자이너', domain: 'prada.com' },
  { name: 'Balenciaga', ko: '발렌시아가', cat: '스트리트/디자이너', domain: 'balenciaga.com' },
  { name: 'Maison Margiela', ko: '메종 마르지엘라', cat: '스트리트/디자이너', domain: 'maisonmargiela.com' },
];
